### ISSUE TITLE
Spotlight not working correctly with dev feature

### ISSUE THREAD

**Issue by anotherlusitano** [coffeeispower/woomer#6]
Instead of an area getting highlighted, its highlighting the entire screen 

[what happen](https://github.com/coffeeispower/woomer/assets/108989500/c12b3a2f-2b15-4c0c-835f-84e3696e7a3f)

**Comment by coffeeispower** [comment]
In dev mode it loads the shader from the file system from the current working directory, you have to be at the root of the project, you can't be inside the target directory.
