### ISSUE TITLE
GLFW can't load `libwayland-client` in the devShell

### ISSUE THREAD

**Issue by jacekpoz** [coffeeispower/woomer#8]
clone woomer, `nix develop` and `cargo run`

this is the output (at least for me):
```
     Running `target/debug/woomer`
INFO: Initializing raylib 5.0
INFO: Platform backend: DESKTOP (GLFW)
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
WARNING: GLFW: Error: 65544 Description: Wayland: Failed to load libwayland-client
WARNING: GLFW: Failed to initialize GLFW
Segmentation fault (core dumped)
```

you most likely installed something system wide and forgot to add it to the shell

sorry for making so many issues, I'm a bit tired for doing these myself right now

I'll look into them later (tomorrow or on wednesday) if they're not fixed yet though

**Comment by coffeeispower** [comment]
I forgot to inherit `LD_LIBRARY_PATH` from `commonArgs` on the nix flake, i'll fix it right away.
Thanks!
